Network:
  epochs: 100
  batch_size: 16
  n_steps: 500
  dataset: "DVS128Gesture"
  data_path: "../datasets/DvsGesture"
  rule: "SGBP_SSL"
  lr: 0.0005
  loss: "kernel"
  n_class: 11
  tau_m: 5
  tau_s: 3
  model: "LIF"

Layers:

    conv_1:  #32*32   #128*128
      type: "conv"
      in_channels: 2
      out_channels: 16
      kernel_size: 3
      weight_scale: 1
      padding: 1
      threshold: 1
      norm: False

    pooling_1:
      type: "pooling"
      kernel_size: 2
      threshold: 1

    conv_2:  #16*16  64
      type: "conv"
      in_channels: 16
      out_channels: 32
      kernel_size: 3
      weight_scale: 1
      padding: 1
      threshold: 1
      norm: False

    pooling_2:
      type: "pooling"
      kernel_size: 2
      threshold: 1

#    dropout_0:
#      type: "dropout"
#      p: 1

    conv_3: #8*8  32
      type: "conv"
      in_channels: 32
      out_channels: 64
      kernel_size: 3
      weight_scale: 1
      padding: 1
      threshold: 1
      norm: False

    pooling_3:
      type: "pooling"
      kernel_size: 2
      threshold: 1   #4*4  16



    FC_1:
      type: "linear"
      n_inputs: 1024   #1024
      n_outputs: 300
      weight_scale: 1
      threshold: 1



    FC_2:
      type: "linear"
      n_inputs: 300      #1024
      n_outputs: 11
      weight_scale: 1
      threshold: 1

