Network:
  epochs: 100
  batch_size: 100
  n_steps: 5
  dataset: "FashionMNIST"
  rule: "SGBP_SSL"
  data_path: "../datasets/fashionmnist"
  lr: 0.0005
  loss: "kernel"
  n_class: 10
  tau_m: 5
  tau_s: 3
  model: "LIF"

Layers:
  hidden_1:
    type: "linear"
    n_inputs: 784
    n_outputs: 400
    weight_scale: 1
    threshold: 1

  hidden_2:
    type: "linear"
    n_inputs: 400
    n_outputs: 400
    weight_scale: 1
    threshold: 1

  output:
    type: "linear"
    n_inputs: 400
    n_outputs: 10
    weight_scale: 1
    threshold: 1
