Network:
  epochs: 50
  batch_size: 50
  n_steps: 30
  dataset: "NMNIST_Spiking"
  rule: "SGBP_SSL"
  data_path: "F:/pycharmproject/spiking_unet11/spiking_unet/one_more_try/TSSL-BP/preprocessing/NMNIST/2312_3000_stable/"
  lr: 0.0005
  loss: "kernel"
  n_class: 10
  tau_m: 8
  tau_s: 4
  model: "LIF"

Layers:
  conv_1:
    type: "conv" # 34
    in_channels: 2
    out_channels: 12
    kernel_size: 5
    weight_scale: 1
    padding: 1
    threshold: 1
    norm: False

  pooling_1:  # 16
    type: "pooling"
    kernel_size: 2
    threshold: 0.5

  conv_2: # 12
    type: "conv"
    in_channels: 12
    out_channels: 64
    kernel_size: 5
    weight_scale: 1
    padding: 0
    threshold: 1
    norm: False

  pooling_2: # 6
    type: "pooling"
    kernel_size: 2
    threshold: 0.5

  output:
    type: "linear"
    n_inputs: 2304
    n_outputs: 10
    weight_scale: 1
    threshold: 1

